language: node_js
node_js:
- stable

env:
  global:
    - CC_TEST_REPORTER_ID=7f3912562bd2595b67588ddd441099a34c41a012442ccdda9eab770fc660dfdc

install:
- yarn

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
- yarn build
- yarn test --coverage

after_success:
  - npx semantic-release
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT