language: node_js
node_js:
- stable
install:
- yarn
script:
- yarn test
deploy:
  on:
    tags: true
  api_key:
    secure: Ps/XkQuDqO24nRvRbM66udnxEY6xb+h9IYHlgtYsqS3w6Z/DOp0ectkMKe7gXzpOBbVt7RGkcLW2nfnZSp63AMGwsA1JrjXO31ARD3HFTXOqDcYCtrZ+8ABpUkzjCsXsTiOMoh741PFoqvCON83KK0CMFHxjb+G2mTYgS787XEL/p45HvdMU9wJhyZuNqpSXm1Y7jFKZdMlIPs0GVkyY9H20vS7Au8qt3ceuDm53J+zdDl40HkMvfrZPnv69laOwXSvhbW1fvNk7EfBPKpDeePmOYMc6A+/Jc5EOZHUcOh0mIfBupiz3P9hd8nyQJRG81qlE2rRm+3H94MiF5bVjv75OuJtcD3F8uhFft7LkAg5RBnfcy8z+cMuv0dfzsbSWuAbyOZNWtGHfwHYzoXnRBSHbd0fqvLymVT+Nub4HC7iU7bIq8ugd4LxoryeUeR9Tz0oJRmyQG2vjX5RfsZn293k5ZM9TBQBLeotP6MmgbEym1+TxJnxm7y2Sy0UbPkSjvyjn91mZlw3ajMs5pIxhanD3uaYs1p9hfjwdcKmthhIjfastVHK3Fbwk7yQDTJmkKKH35GjQw/riG3N6IAYRxWBjuXrq5bq62XSGcPp+yF8Pri+NvNDYLA0ciRawrn8yEn5wImg9Nv/hjvsYnwxpsgfVf1XKsENuNvqUS49gX04=
